# Generated by Django 6.0.4 on 2026-06-02 00:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='demande',
            name='type_service',
            field=models.CharField(choices=[('plomberie', 'Plomberie'), ('electricite', 'Électricité'), ('reparation', 'Réparation'), ('peinture', 'Peinture'), ('climatisation', 'Climatisation'), ('menuiserie', 'Menuiserie'), ('autre', 'Autre')], max_length=50),
        ),
    ]
