# Generated by Django 6.0.4 on 2026-07-26 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_demande_type_service'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='specialite',
            field=models.CharField(blank=True, choices=[('plomberie', 'Plomberie'), ('electricite', 'Électricité'), ('reparation', 'Réparation'), ('peinture', 'Peinture'), ('climatisation', 'Climatisation'), ('menuiserie', 'Menuiserie'), ('autre', 'Autre')], help_text="Métier de l'artisan (non utilisé pour les clients)", max_length=50),
        ),
    ]