# Generated by Django 6.0.4 on 2026-07-29 00:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_alter_user_photo'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('nouvelle_offre', 'Nouvelle offre'), ('offre_acceptee', 'Offre acceptée'), ('nouveau_message', 'Nouveau message'), ('nouvel_avis', 'Nouvel avis')], max_length=20)),
                ('message', models.CharField(max_length=255)),
                ('lien', models.CharField(blank=True, max_length=255)),
                ('lu', models.BooleanField(default=False)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('destinataire', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-date_creation'],
            },
        ),
    ]