# Generated by Django 6.0.4 on 2026-08-20 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_message_latitude_message_longitude_message_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='bio',
            field=models.TextField(blank=True, help_text="Présentation affichée sur le profil public de l'artisan", max_length=1000),
        ),
        migrations.AddField(
            model_name='user',
            name='competences',
            field=models.CharField(blank=True, help_text="Compétences de l'artisan, séparées par des virgules (ex: Installation Électrique, Domotique)", max_length=500),
        ),
    ]