# Generated by Django 6.0.4 on 2026-08-22 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_user_bio_user_competences'),
    ]

    operations = [
        migrations.AddField(
            model_name='demande',
            name='latitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='demande',
            name='longitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='demande',
            name='urgent',
            field=models.BooleanField(default=False, help_text='Demande à traiter en priorité (affichée avec un badge Urgent)'),
        ),
    ]