# Generated by Django 6.0.4 on 2026-08-25 02:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_demande_latitude_demande_longitude_demande_urgent'),
    ]

    operations = [
        migrations.AddField(
            model_name='demande',
            name='date_debut',
            field=models.DateTimeField(blank=True, help_text="Date à laquelle une offre a été acceptée (passage à 'En cours')", null=True),
        ),
        migrations.AddField(
            model_name='demande',
            name='date_fin',
            field=models.DateTimeField(blank=True, help_text='Date à laquelle la mission a été marquée terminée', null=True),
        ),
    ]