# Generated by Django 6.0.4 on 2026-08-31 00:58

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_evaluation_date_reponse_evaluation_reponse_artisan'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='date_soumission_verification',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='date_traitement_verification',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='document_verification',
            field=models.FileField(blank=True, help_text="Pièce d'identité ou justificatif professionnel (CIN, matricule fiscal...)", null=True, upload_to='verifications/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png', 'pdf'])]),
        ),
        migrations.AddField(
            model_name='user',
            name='motif_rejet',
            field=models.CharField(blank=True, help_text="Raison du rejet communiquée à l'artisan (visible seulement si rejeté)", max_length=255),
        ),
        migrations.AddField(
            model_name='user',
            name='statut_verification',
            field=models.CharField(choices=[('non_soumis', 'Non soumis'), ('en_attente', 'En attente de validation'), ('verifie', 'Vérifié'), ('rejete', 'Rejeté')], default='non_soumis', max_length=20),
        ),
        migrations.AlterField(
            model_name='notification',
            name='type',
            field=models.CharField(choices=[('nouvelle_offre', 'Nouvelle offre'), ('offre_acceptee', 'Offre acceptée'), ('nouveau_message', 'Nouveau message'), ('nouvel_avis', 'Nouvel avis'), ('verification', 'Vérification identité')], max_length=20),
        ),
    ]