# Generated by Django 6.0.4 on 2026-08-31 01:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_user_date_soumission_verification_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Signalement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('motif', models.CharField(choices=[('spam', 'Spam ou publicité'), ('contenu_inapproprie', 'Contenu inapproprié'), ('arnaque', 'Arnaque ou fraude suspectée'), ('comportement', 'Comportement abusif'), ('autre', 'Autre')], max_length=30)),
                ('description', models.TextField(blank=True, max_length=500)),
                ('statut', models.CharField(choices=[('nouveau', 'Nouveau'), ('traite', 'Traité'), ('rejete', 'Rejeté')], default='nouveau', max_length=20)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('date_traitement', models.DateTimeField(blank=True, null=True)),
                ('auteur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='signalements_envoyes', to=settings.AUTH_USER_MODEL)),
                ('demande_signalee', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='signalements', to='core.demande')),
                ('utilisateur_signale', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='signalements_recus', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-date_creation'],
            },
        ),
    ]